### ISSUE TITLE
Uncaught TypeError: Argument 1 passed to SDK\Cache::__construct() must be of the type string, null given

### ISSUE THREAD

**Issue by dktapps** [OSTC/php-sdk-binary-tools#16]
```
Fatal error: Uncaught TypeError: Argument 1 passed to SDK\Cache::__construct() must be of the type string, null given, called in C:\projects\php-sdk\lib\php\libsdk\SDK\Config.php on line 128 and defined in C:\projects\php-sdk\lib\php\libsdk\SDK\Cache.php:14
Stack trace:
#0 C:\projects\php-sdk\lib\php\libsdk\SDK\Config.php(128): SDK\Cache->__construct(NULL)
#1 C:\projects\php-sdk\lib\php\libsdk\SDK\Config.php(165): SDK\Config::getKnownBranches()
#2 C:\projects\php-sdk\bin\phpsdk_deps.php(99): SDK\Config::setCurrentBranchName('7.2')
#3 {main}
  thrown in C:\projects\php-sdk\lib\php\libsdk\SDK\Cache.php on line 14
```

Using the following:
```
C:\projects\php-sdk\bin\phpsdk_deps.bat --update --branch 7.0 --arch x64 --dir C:\projects\php-src\deps
```
from the drive root (v2.0.9)

**Comment by weltling** [comment]
Hi, thanks for the report. There is no such `--dir`, it's likely `--deps` what was meant. Would it fix it for you? 

Type hints should be checked, too, i'd say. 

Thanks.

**Comment by dktapps** [comment]
ah yes, my bad. Thanks.
