### ISSUE TITLE
Failed to unpack, error code '19'

### ISSUE THREAD

**Issue by ghost** [OSTC/php-sdk-binary-tools#7]
```
d:\php-sdk\phpmaster\vc14\x64\php-src-php-7.0.14
$ phpsdk_deps --update --branch master

Configuration: master-vc14-x64-staging

Processing package apache-2.4.23-vc14-x64.zip
Processing package c-client-2007f-vc14-x64.zip
Processing package dirent-20080629-vc14-x64.zip
Processing package fbclient-2.5-nocrt-x64.zip
Processing package freetype-2.7.0-vc14-x64.zip
Processing package glib-2.49.4-vc14-x64.zip
Processing package ICU-57.1-vc14-x64.zip

Fatal error: Uncaught SDK\Exception: Failed to unpack, error code '19' in D:\php-sdk\lib\php\libsdk\SDK\Dependency\Package.php:54
Stack trace:
#0 D:\php-sdk\lib\php\libsdk\SDK\Dependency\Manager.php(68): SDK\Dependency\Package->unpack('D:\\php-sdk\\.tmp...')
#1 D:\php-sdk\bin\phpsdk_deps.php(185): SDK\Dependency\Manager->performUpdate(NULL)
#2 {main}
  thrown in D:\php-sdk\lib\php\libsdk\SDK\Dependency\Package.php on line 54

```

**Comment by weltling** [comment]
Thanks for the report. First guess - possibly a network issue, so the corresponding package was broken. Otherwise, is this reproducable in some way?

Thanks.

**Comment by ghost** [comment]
Yes. it relate to network issue. i force redownload. then working correct.
